### ISSUE TITLE
HTML child templates not generated

### ISSUE THREAD

**Issue by fredrb** [keithwhor/nodal#101]
Using the latest rev (commit 5ca98e0) HTML is not being generated correctly when creating new projects. 

After a clean new install (using default answer to all questions) I get this as plain text back when hitting http://localhost:3000:

    {{= this.partial('head.html') }}
    {{= this.child() }}

Apperently this is happening during template generation in method`constructor(app, fn, children)`. This  was changed from `constructor(app, fn)` .

And now for some reason, this method isn't rendering the children correctly:

    this.app.template('layout.html', 'index.html').generate(
      this.params,
        {
          test: this.params.query.test,
          name: 'My Nodal Application'
        }
    )

**Comment by intabulas** [comment]
So this is occurring because during a `nodal new` the version of nodal being installed (nodal@latest) into node_modules doesn't have the new template changes in it yet and your app will try and use that version by default. 

A quick fix (until  we push a new rc to npm) is to cd into your apps node_modules, rm -rf nodal and the symlink in the git clone of master your were using  `ln -s <path to your clone of nodal> .`
