### ISSUE TITLE
Roadmap and project development insights

### ISSUE THREAD

**Issue by goliatone** [keithwhor/nodal#11]
I just ran into `nodal` via echojs, saw the intro video and looked around the source code. I'm actually really excited about the project. So far I like what I've seen but I still have to take it for a run. 
Here's the thing, I'm trying to decide wether I **should spend any time** on it or not, or **when** I should spend that time- now or after X feature is implemented.

Is there a roadmap you could share or that I have not seen yet? Is there an official blog where I could follow progress/updates/reasoning? I've seen some of the github issues but I don't think github is the  appropriate medium for this.

For instance, I'm curious as to why you decided to implement- I think- the ORM from scratch. Personally is one of the key factors for me to consider using a framework or not. 

thanks

**Comment by keithwhor** [comment]
I assume you saw me talking myself for the past week :smile:;
https://github.com/keithwhor/nodal/issues/10

You can start spending time on Nodal now! The features that are most stable are Routing, Controllers, Models, Migrations, Scheduling, Initializers and the ORM. Be careful with writing your own Middleware, I may refactor it.

I canned a bunch of experimental stuff before 0.5.x that wasn't well tested / used. I'll be adding *more* features to Controllers, Models and the ORM but most of the minimal feature set is locked.

I'll be creating more of the community tooling for Nodal in the coming month (blog, etc.). Stay tuned. I'll keep this issue open and let you know as things are implemented. Still have to generate API docs and write an intro guide (not just rely on YouTube).

Re: The ORM. It's from scratch because, well, it was fun. I had an idea of how I wanted the developer interface to work (much like Django's ORM), how I wanted it to be able to interface with Controllers / Models / Etc., and I already had a ton of SQL generation logic done from previous iterations + migration support. I've refactored the ORM fully about three times now, but I'm really happy with where I've arrived with it. The most difficult part has actually been determining what the developer interface should look like, and how people would reason about queries as they're writing them.

I'm actually really happy with the implementation. Every chained method call creates a new Composer that references its parent. When queries are finally executed, we iterate up through the created linked list and "squash" the commands together (reduction) to determine the SQL query, which is generated as a bunch of nested subqueries. You can theoretically branch off of a query at any point and still generate a valid query.

For example,

```
let q = Tweet.query().where({id__gt: 5});
q.where({id__lte: 9}).end((err, tweets) => /* all tweets from 6-9 */);
q.orderBy('body', 'DESC').limit(10).end((err, tweets) => /* 10 tweets, id > 5, by body DESC */);
```

**Comment by keithwhor** [comment]
BTW: One thing I'd really like to work on in the roadmap is tests. The ORM has pretty thorough integration tests, but everything else is lacking.

I also want to set up a scaffolding class / module for testing *within* a Nodal Project. That will probably come sooner rather than later, as I'm already writing production systems and need an idiomatic way to write tests.

**Comment by goliatone** [comment]
Yes, i did read all the issues and followed the monologue, it was informative and good to get a sense on how things get to be. 

Ok, I will give a try, have to find the right project to do so, some prototype or something that can tolerate the risk. 

Thanks for the update

**Comment by keithwhor** [comment]
Available in ROADMAP.md :)
