### ISSUE TITLE
Unnecessary immediate invocation

### ISSUE THREAD

**Issue by Pyrolistical** [keithwhor/nodal#110]
http://stackoverflow.com/questions/20149010/immediate-invocation-in-node-js-modules

in every file... eg. https://github.com/keithwhor/nodal/blob/master/src/server.js

**Comment by keithwhor** [comment]
Unnecessary, yes. Used for developer readability with the CommonJS module system (`require`). This way there's no ambiguity as to where a `module.exports` statement is, and the value it exports is always the return of the IIFE.

**Comment by schahriar** [comment]
Although I do agree with you that IIFE is not critical or does not change how modules are given a scope through the VM module (which a require call uses) this was mainly a design decision by @keithwhor. Similar to choosing classes over prototypes. An experienced NodeJS developer might feel weird about it but Nodal was developed for humans in that way and I believe the final style has turned out great.

**Comment by Pyrolistical** [comment]
Abandon all hope with arbitrary opinions.

This project is not worth spreading unless you agree with all these unpopular opinions and use Postgres.
