### ISSUE TITLE
Websocket for API services.

### ISSUE THREAD

**Issue by chesstrian** [keithwhor/nodal#14]
Hi @keithwhor, thanks for this amazing framework, I'm really happy to finally have a Django-like ORM to work with in Node JS.

I just want to ask you, What are your thoughts about Websocket support?, It would be great if API server works with Websocket, updating subscribers when a given model have CUD operations.

**Comment by keithwhor** [comment]
I had WebSocket support before the 0.5.x release. (It's actually in the early release candidates.)

I removed it for a list of reasons;

1. I couldn't think of a reasonable design pattern for dealing with socket messages.

I didn't have a use case, meaning it was hard for me to reason about. I *completely disagree* with the pattern of just executing a Controller from a WebSocket request, because why not just use an XHR? RESTful endpoints are designed to be stateless. WebSocket connections are stateful by definition. Which means that WebSockets need their own interface and design patterns. Do I use use socket.io, or emulate the socket.io workflow? Undecided.

2. I'm not going to use a technology just because I can, when the benefit it adds (reduction in request load due to no HTTP headers after initial handshake, avoidance of repeated polling or longpolling) is a premature optimization at best.

3. There's also scalability issues - while you should be able to horizontally scale a RESTful server no problem (no shared state), scaling a WebSocket server requires some central repository of shared state (i.e. You'd need a key-value store like Redis). I don't want to start down that path this early in development because they're very complex problems to solve.

4. The WebSocket module I was using added unnecessary install time to the package when it was only experimental.

I definitely, *definitely* want to approach this again in the future. But I'd have to have a really solid example use case from a user, and their needs and decide whether it's worth generalizing to the entire package and how I would do so. I could probably suggest suggest using something like socket.io in an initializer if you're only running one server.

**Comment by chesstrian** [comment]
One thing I'd like to do with websocket is to broadcast changes over a model to anyone subscribed to changes in such model. This is a kind of generalization, is this something you consider might be in the framework?. The application in my case would be:

Two admins are seeing a manager view for User model, something like a table with all user in the system. When one of the admins create, update or delete a user, the other admin can see changes reflected in the table without reloading the page. I'd like to see how this can be currently implemented.

**Comment by keithwhor** [comment]
Nodal is not currently a realtime framework, very purposefully. The complexities associated with model subscription are immense. I'm not excluding the possibility of this sort of functionality, but it probably won't exist in the way you're used to seeing it if it does get implemented.

If you'd like to build something yourself, inherit from `Nodal.Model` and extend the `save` method:

```
class SubscribedModel extends Nodal.Model {

  save(callback) {

    // get changed fields
    let changedFields = Object.keys(this._changed).filter(f => this._changed[f]);

    // call save from Nodal.Model
    super.save((err, model) {

      // if no error, broadcast model, id and changed fields
      !err && someSocketModule.broadcast('model:changed', {
        model: this.constructor.name,
        id: this.get('id'),
        data: changedFields.reduce((o, f) => {
          o[f] = this.get(f);
          return o;
        }, {})
      });

      // call original callback
      callback(err, model);

    });

  }

}
```

**Comment by shawn-simon** [comment]
Random guy chiming in here- unfortunately non-realtime systems are a thing of the past. There's no benefit to running XHR requests anymore, it'll just be a matter of time until you wished all of your requests were stateful.

**Comment by keithwhor** [comment]
Respectfully disagree. The benefits of realtime systems for the majority of webapps are washed away by the increase in complexity of development. Realtime communication is being applied to problems it needn't be used to solve. The dust will settle, realtime apps will have their niche (or certain portions of an application will be realtime), and foundational web architecture will remain strong. Stateless protocols have their benefits. :)

**Comment by sidhuko** [comment]
I like the example @keithwhor. Would be nice to see community bring an application server (like your angular example), using standards like [DDP](https://atmospherejs.com/meteor/ddp) or Firebase, to run as a separate microservice, or, the application server if your SPA is only using realtime data. An API server should always handle the transactions between server though so things like GraphQL can be implemented in one place.

Awesome framework by the way. Just my luck I'd been researching them all day for a quick website build and this was top of HN! Will be starting tonight :+1:

**Comment by keithwhor** [comment]
@sidhuko Thank you! Glad I could help. :smile: 

@chesstrian I'll leave this open and keep logs of ideas / proposed changes as I develop WS integration.

**Comment by toddself** [comment]
@chesstrian you can use [Server-Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) to do that without the unnecessary overhead of a socket connection.

@shawn-simon real time does not mean sockets.  Very few applications benefit from realtime data coming IN from the client -- out from the server, definitely.  There are better tools than sockets for that though.

I agree with @keithwhor that sockets bely an entirely different set of thought and design around their use, dataflow and routing -- a RESTful approach to socket interactions is going to hurt way more than it helps in the long run

**Comment by niallobrien** [comment]
I agree with the the above statements, just look at Meteor.js; it's realtime by default but it's very easy to hit the scalability-ceiling and normally requires a refactor from a monolithic architecture to a microservices approach all while being very mindful of what does & doesn't need to be realtime.
If you absolutely need websocket support, I'd personally suggest handling this functionality off to a third-party service such as [pusher.com](http://pusher.com) so you don't have to worry about scaling your realtime infrastructure and can continue to focus on the core features of your app. If realtime is a core-feature, then perhaps nodal.js isn't for you, and that's okay. You could always take a microservice approach with [Firebase](https://www.firebase.com) and [Firebase Queue](https://github.com/firebase/firebase-queue) to listen for jobs on a Firebase queue endpoint and hand the job off to microservices for processing.

**Comment by keithwhor** [comment]
So I'm going to close this for now. With the way Nodal is going, not planning on supporting stateful connections in the core package. Will have another solution, but will have to pause this.

**Comment by troyconquer** [comment]
Just wanted to touch base again on this. @keithwhor , have you run into any use cases lately or new thoughts on how to tackle "realtime" for Nodal applications?

I know you've been busy, but I figured I'd ask. 

I have a realtime requirement on my application. We are doing "auto-saving" in our web-client, and want to ensure our client2  is updated when client1 makes changes to a mutual resource. Given the discussion it sounds like the desired solution is to have a micro-service that handles server->client "realtime-ness" . I guess I'd plan on using Redis (already in use) to pub/sub between the Nodal API server and TBD Realtime Server.

Thinking out loud and very open to 2 cent.
