### ISSUE TITLE
Babel support

### ISSUE THREAD

**Issue by lolmaus** [keithwhor/nodal#196]
Node has made great progress, but it's still far behind latest ES.

There is well-maintained [babel-preset-node5](https://github.com/leebenson/babel-preset-node5) that transpiles only the parts not supported by Node 5 (e. g. async/await, decorators). I really wish to use it in my code.

I've seen https://github.com/keithwhor/nodal/pull/34, maybe it can be revived? Or just start from scratch!

**Comment by keithwhor** [comment]
Unfortunately for people excited to get their hands on newer ECMAScript features, I have no interest in polluting the toolchain. Nodal works because it's opinionated and there is ideally only one obvious and correct way to do things. While async and await are great features, Nodal's codebase was not designed with these features in mind, so it does not make sense to tack them on haphazardly. Nodal will progress in lock-step with Node.js.
