### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by p1nox** [keithwhor/nodal#201]
First, I think the idea of the framework in general is really cool :+1:, but I might be missing something, is there any plan to add MongoDB into the equation?

**Comment by keithwhor** [comment]
Not at present time, no. PostgreSQL is a pretty reasonable one-size-fits-all solution, and the goal with Nodal is to empower developers to create API services as quickly as possible by removing decision fatigue and the cognitive overhead it creates.

If you'd like MongoDB support, I encourage you to write an adapter. :)

http://www.aptuz.com/blog/is-postgres-nosql-database-better-than-mongodb/

**Comment by kayazinc** [comment]
I was searching for an API server and I found Nodaljs.  Nodaljs is great, it has most of the features that I am looking for in an API server.  Unfortunately the only thing that is lacking of is the support of MongoDB.

Many companies and developers are moving away from RDMS to non-sql database because of the flexibility in term of development.  I hope Nodaljs can consider support MongoDB as one of the database.  Thanks.
