### ISSUE TITLE
use of require within module.exports

### ISSUE THREAD

**Issue by reggi** [keithwhor/nodal#216]
Just got one of your emails so I'm hoping this feedback is solicited. 

I'm looking through the docs and I'm seeing a lot of references to `module.exports` and calling `require` through your codebase. These two things erk me a bit because they don't mesh well with ES6. 

[In ES6 `import` needs to be a top level function](http://stackoverflow.com/questions/36724290/cannot-call-a-class-as-a-function?noredirect=1#comment61034608_36724290), and those pesky requires are a bit odd.

Thoughts on this would be appreciated.

This is so odd to me...

```js
module.exports = (() => {

  'use strict';

  const Command = require('cmnd').Command;

  const fs = require('fs-extra');
  const path = require('path');
  const inquirer = require('inquirer');
  const inflect = require('i')();
  const colors = require('colors/safe');
  const async = require('async');
  const http = require('http');
```

**Comment by keithwhor** [comment]
Hey! Thanks for checking everything out.

You're right. We can change this design pattern, and should in the future.

Ideally, imports first, immediately followed by the module.exports line. Would like to keep the IIFE there for now until we're using native exports. I haven't been following node 5.x development lately, is there any idea when we'll see import / export land?

**Comment by reggi** [comment]
@keithwhor Thanks for the quick response. Not exactly sure when it will land in as official syntax, I've been using babel in my personal projects. Are you against using babel?

**Comment by keithwhor** [comment]
No problem. Working all the time. :)

Yeah, I am. For the front-end I can see why it makes sense --- browser vendors have wildly different implementations. Babel fills the same niche jQuery used to, except for higher level syntax instead of the DOM API.

Here I want to avoid build steps because it's *very* important to me that the solution I provide is lightweight and easy to debug. I'd rather stay in the (still very fast moving!) world of V8.
