### ISSUE TITLE
Does it work with MySQL?

### ISSUE THREAD

**Issue by hguillermo** [keithwhor/nodal#54]

**Comment by CoolVoltage** [comment]
It supports only for PostgreSQL as of now. Probably support for MYSQL is in the roadmap, not sure though!

**Comment by hguillermo** [comment]
Maybe I can work on MySQL support. I am sure there many people there waiting for MySQL support.

**Comment by nrempel** [comment]
At a glance, it looks like you would need to modify https://github.com/keithwhor/nodal/blob/master/core/required/db/database.js#L16 to set `this.adapter` based on the config instead of hardcoding postgres.

Then, add a MySQL adapter here: https://github.com/keithwhor/nodal/tree/master/core/required/db/adapters that inherits from https://github.com/keithwhor/nodal/blob/master/core/required/db/adapter.js (like the postgres adapter).

@keithwhor love how easy it is to navigate the source code btw :smile:

**Comment by keithwhor** [comment]
@nrempel Thanks!

Yep, that's correct. The default adapter class has a lot of generic SQL. You'll need to change some things (the escape character, etc.). I planned it *roughly* to be extensible to MySQL and SQLite, but because I haven't started working on other adapters there might be some architecture you need to shift around. Also; Array support will be tricky to navigate. (And comparators that rely on it.)

I think in general there needs to be a larger Database roadmap with tools, because I think it would be *great* to be able to generate a schema.json automatically from a pre-existing database as well.

**Comment by intabulas** [comment]
@nrempel also a few hardcoded postgres:// in the cli migrations that would need to be sorted

**Comment by hguillermo** [comment]
Thank you guys. That is a good start.

**Comment by fredrb** [comment]
@keithwhor Do you have plans to keep other DBs adapters within Nodal's source or should they be downloaded as dependency/plugin through npm?

**Comment by keithwhor** [comment]
@fredrb Sorry, missed this. If somebody else develops them, maybe NPM. But can add a few to the project by default.

Archiving this as it's not a priority at present time.

**Comment by cwiese** [comment]
Has anyone tried this?   I would like to use this over TeraData (with maybe Memcache in between) .... my options are: write my own or go with java

**Comment by dimka3210** [comment]
Make MySQL please. Thx @keithwhor
