### ISSUE TITLE
Proposal: find_by for models

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#74]
Creating an issue for discussion, mentioned in the chat before but I think it has scrolled off.

This is a proposal for a `find_by` method to be added to the `model.js` to simplify fetching a model by a non id key. I am not trying to propose a proliferation of `find_by_X` at all, just a simplification.

As a example, using part 3 of the video the AccessToken#login has the following

```javascript
User.query()
    .where({username: params.body.data.username})
    .end(....)
```
I am proposing a shorthand

```javascript
User.find_by({username: params.body.data.username}, (err, models) => {
});
```
And yeah upfront it adds no benefit other than a simplified api (and does not return a composer)..

Rough single key only test impl  https://gist.github.com/intabulas/0f1a529ecb255d7a4952

**Comment by schahriar** [comment]
I am not against this but since this goes beyond the scope of Nodal I am gonna try to explain the advantage behind using a step by step query builder and why it **may be** a bad practice to introduce shorthands. If you consider a small application built on top of a command based query system (e.g. `find_by`, `find_one`) it would work just fine and the code would be cleaner (the code above shows that) but what happens when you try more complex queries? In most cases your API queries are going to get more and more complex and you can use a combination of both methods. But imagine you've already built an entire interface on top of shorthands and decided that you needed a much larger query:
```javascript
User.find_by({
    username: params.body.data.username,
    password: ...,
    name: params.body.data.name,
    ...
}, (err, models) => {
...
```
Later on you consider incorporating abstraction (since with the large API your codebase is equally large) this means you'll pass the query directly to the file in object format:
```javascript
...
User.find_by(query, (err, models) => {
```
Now here is the catch. You finally realize you need `sort` and `paginate` ... functions. Those functions aren't available in `find_by` (unless we make the function more complex which then requires double the amount of maintenance work) so you'll have to go back to the normal query and possibly replace every instance of `find_by` with the good ol' query builder. Using the builder also allows for much better modularity.

So why not enforce it from the get go?
We probably should enforce at as a design style to help developers from making the mistake that I've at least made on many occasions.

Why not ignore this?
*Users need some direct contact from the database and methods such as `find_by` and `find_one` are useful interfaces that simplify these queries.

So if we want an implementation it should be for internal access and simple queries making it clear that it isn't meant to be used directly.

Here are references to my experience with Sails Waterline and complex queries:
Query creator on top of the query builder https://github.com/schahriar/Galleon/blob/master/query/get.js
Complex queries https://github.com/schahriar/Galleon/blob/master/query/get.build.js

**Comment by intabulas** [comment]
I really like and prefer the composer myself.. Too much history with command based method_missing magic ;). I was pondering this purely as a shorthand way to find related models (like User in AccessToken), very much like find but when you don't want to search on id. 

My original test forcibly viewed this as a limit 1 type of short hand (ie return models[0]) but I removed that at some point while playing around. And your right that has down the road complications (sort, paginate)

While I can't disagree it may set a bad precedent for a proliferation of command queries, I guess you can say the same thing about model#find (totally ignoring the fact things likes routes and such are forcibly centered around model id)

But this was created for discussion, which I am throughly enjoying

**Comment by schahriar** [comment]
I myself don't see much wrong with introducing `find_by` in the structure but that introduces an alternative syntax which would probably require some sort of `find_and_sort_by` or probably a better way of doing commands like that or perhaps even use argument parsing to do this auto-magically:
```javascript
...
function find_by() {
   let args = Array.prototype.slice.call(arguments);
   let callback = args.pop();
   let query = args.shift();
   // See what we have left
   if(args.length >= 1) {
       let sort = args.shift();
       ...
   }
   // Construct query here and this simplifies the entire thing to one function.
}
```
**This is akin to C++ function overloading in a way but does that through parsing args**

I think we should keep this as a long-term discussion. I can foresee many people in the future opening issues for this and making a solid design decision with the thought process involved would be the point of this issue. All suggestions and arguments are welcomed.

**Comment by intabulas** [comment]
agree on the last paragraph whole heartedly

**Comment by keithwhor** [comment]
Well, for one, it would be `Model.findBy`, not `find_by` ;)

Two, I don't really like it because there should ideally be one (and only one) correct way to do things. I will add a `Composer#first(callback)` method to composer that's used like this;

```
User.query()
  .where({username: 'some_name'})
  .first((err, user) => {
    this.respond(err || user);
  });
```

This avoids having to call `.limit(1)` and can automatically return a `notFound` error if there is no first result. (Instead of a successful call that just results in no records.)

**Comment by schahriar** [comment]
@keithwhor can you do this?
```javascript
User.query({username: 'some_name'}).first((err, user) => {
    this.respond(err || user);
  });
```
That would save two calls `where`, `exec`.

**Comment by keithwhor** [comment]
Would rather not for now. Then there's two ways to do a `Composer#where`, one being a shortcut. I'm not totally opposed to shortcuts, but I anticipate the next request after that is a shortcut for limit, or orderBy, etc. etc. Potential rabbit hole.

**Comment by keithwhor** [comment]
I'll close this ticket after I implement `first()`, btw.

**Comment by intabulas** [comment]
@keithwhor so basically first() combines a limit(1) and end()

**Comment by keithwhor** [comment]
Yep. Going to close this now that `.first()` is implemented.
