### ISSUE TITLE
How to throw the data from the database into templates?

### ISSUE THREAD

**Issue by kulakowka** [keithwhor/nodal#79]
In the [docs](https://github.com/keithwhor/nodal#branding-server) you have written:
> If you need to grab live data from an API, send asynchronous non-blocking requests to your API Server.

Could you give some examples? Must i use a cross-server queries using [superagent](https://github.com/visionmedia/superagent) or [request](https://www.npmjs.com/package/request)? 
or is there some other way to do http-queries using your framework?

**Comment by keithwhor** [comment]
I'd recommend `request` for now. I'd like to build something in to Nodal for taking care of this, because it's likely somebody will be sending external requests.

The suggested architectural patterns is to have a separate API server, so when you're running it you'd query it via something like the `request` module, yes. And then incorporate that result in your `Controller#render()` call.

**Comment by kulakowka** [comment]
Thanks @keithwhor. I now understand.
