### ISSUE TITLE
Support pluggable template engines

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#93]
While I Iove [doT](http://olado.github.io/doT/index.html), some folks may be more comfortable with handlebars or haml for an example. Plus doing things like layouts is not straight forward in doT

This issue proposes we allow users to use alternate template engines from npm modules that could be utilized like

```javascript

const SomeTemplateEngineForNodal = require( ... some module name ... );

class App extends Nodal.Application {

  __setup__() {

   this.templateEngine.use(SomeTemplateEngineForNodal)
   ...
 
 }

}
```

The module (and I suggest extracting the current into a module) would be responsible all things that template... ie:  `dot.templateSettings.varname = 'params, data';` like we have in core.

We would still leave doT around as the default and the one used by nodal cli commands

first step would be abstract out doT from the core and make it a module (nodal-template-dot maybe)

discuss.... ;)

**NOTE:** Unless we decided to leave as is (would would be just fine IMHO),  this impacts config/db.json generation and means template choice would need to be visible to Nodal.my.Config

**Comment by keithwhor** [comment]
So here's the thing;

IMO, complex templating logic is an anti-pattern in modern web development. I want to actively discourage people from building monolithic applications with complex templates. If I could have done without including doT itself, I probably would have, but it's just not tenable because you need to have *some* form of templating.

The goal of separating App / Branding / API is to minimize this complexity. Your App should have all of your UI logic and should ideally be an SPA. In this case, we don't use any of Nodal's logic whatsoever. If you're starting to require a lot of complex logic on your "Branding" server, it's worth reconsidering where you're putting it.

**Comment by keithwhor** [comment]
Gonna close this for the reasons mentioned above. Maybe we'll support it in the future, but there's too much cost associated with too little benefit at this point.

**Comment by intabulas** [comment]
k.. I am fine with doT.. I was just thinking about transition.. See  https://gist.github.com/intabulas/07d981d412f53a4da3a1#file-a2-dot-templates-md

**Comment by intabulas** [comment]
So I was about to open an issue to refactor a bit to support the concept of layouts in the controller render()'s per the above doc..  Should I hold off?
